# MIT License

# Copyright (c) 2020 Hongrui Zheng

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

ARG ROS_DISTRO=humble

FROM ros:${ROS_DISTRO}

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        nano \
        vim \
        python3-pip \
        python3-dev \
        libeigen3-dev \
        tmux \
        ros-${ROS_DISTRO}-rviz2 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /sim_ws

# The container is the isolation layer, so f1tenth_gym is installed into the
# system Python rather than a venv: entry points generated by colcon use
# /usr/bin/python3, which would not see a venv-installed gym.
# PIP_BREAK_SYSTEM_PACKAGES is a no-op on humble and required on jazzy.
ENV PIP_BREAK_SYSTEM_PACKAGES=1

# The f1tenth_gym dependency lives outside /sim_ws/src so that bind-mounting
# this repo into the container (see docker-compose.yml) cannot shadow it.
ARG GYM_REF=dev-humble
# Debian-patched pip and RECORD-less distro packages break the install two
# ways: the stock pip's isolated build env can't run the gym's uv_build
# backend (22.04), and pip refuses to replace apt-installed deps like numpy
# (24.04). Install a fresh pip, then let the gym's dependency stack land in
# /usr/local, which takes precedence over the apt copies.
RUN pip3 install --ignore-installed pip

# arm64 + Ubuntu 22.04 (glibc 2.35): PyQt6 6.7.1 is the newest release with a
# compatible aarch64 wheel — newer ones need glibc >= 2.39, so pip falls back
# to the sdist and fails looking for qmake (seen on Apple Silicon). Jazzy and
# later have glibc >= 2.39; x86_64 is unaffected.
RUN if [ "${ROS_DISTRO}" = "humble" ]; then \
        echo 'pyqt6 == 6.7.1; platform_machine == "aarch64"' > /tmp/pip-constraints.txt; \
    else \
        touch /tmp/pip-constraints.txt; \
    fi && \
    git clone --depth 1 --branch ${GYM_REF} \
        https://github.com/f1tenth/f1tenth_gym.git /sim_ws/f1tenth_gym && \
    pip3 install --ignore-installed -c /tmp/pip-constraints.txt -e /sim_ws/f1tenth_gym

COPY . /sim_ws/src/f1tenth_gym_ros

RUN source /opt/ros/${ROS_DISTRO}/setup.bash && \
    apt-get update && \
    if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then \
        rosdep init; \
    fi && \
    rosdep update && \
    rosdep install -i --from-paths /sim_ws/src --rosdistro ${ROS_DISTRO} -y && \
    colcon build --symlink-install && \
    rm -rf /var/lib/apt/lists/*

# Interactive shells come up ready to `ros2 launch`
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc && \
    echo "source /sim_ws/install/setup.bash" >> /root/.bashrc

# foxglove_bridge websocket (connect Foxglove to ws://localhost:8765)
EXPOSE 8765

ENTRYPOINT ["/bin/bash"]
