# MIT License

# Copyright (c) 2020 Hongrui Zheng

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

ARG ROS_DISTRO=jazzy

# Where f1tenth_gym comes from:
#   git   (default) clone GYM_REF from GitHub
#   local copy the nested f1tenth_gym/ clone inside this repo (the layout the
#         native install creates), so uncommitted gym changes can be tested here:
#         GYM_SOURCE=local docker compose build
ARG GYM_SOURCE=git
ARG GYM_REF=dev-jax

# --- gym source stages: only the one selected by GYM_SOURCE is built ---------
FROM ros:${ROS_DISTRO} AS gym-git
ARG GYM_REF
RUN apt-get update && \
    apt-get install -y --no-install-recommends git ca-certificates && \
    rm -rf /var/lib/apt/lists/* && \
    git clone --depth 1 --branch ${GYM_REF} \
        https://github.com/f1tenth/f1tenth_gym.git /sim_ws/f1tenth_gym

FROM ros:${ROS_DISTRO} AS gym-local
COPY f1tenth_gym /sim_ws/f1tenth_gym

FROM gym-${GYM_SOURCE} AS gym-src

# --- the image ---------------------------------------------------------------
FROM ros:${ROS_DISTRO}
ARG ROS_DISTRO

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

# Qt/OpenGL runtime libraries and xvfb let the gym's own renderer run headless
# inside the container (xvfb-run -a python3 examples/waypoint_follow.py); the
# bridge itself never opens a window.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        nano \
        vim \
        python3-pip \
        python3-dev \
        libeigen3-dev \
        tmux \
        ros-${ROS_DISTRO}-rviz2 \
        libxcb-cursor0 libxcb-icccm4 libxcb-keysyms1 libxcb-shape0 libxcb-randr0 \
        libxcb-render-util0 libxcb-xinerama0 libxkbcommon-x11-0 \
        libgl1 libegl1 libopengl0 libgl1-mesa-dri xvfb && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /sim_ws

# The container is the isolation layer, so f1tenth_gym is installed into the
# system Python rather than a venv: entry points generated by colcon use
# /usr/bin/python3, which would not see a venv-installed gym.
ENV PIP_BREAK_SYSTEM_PACKAGES=1

# CPU-only image: keep JAX on the CPU everywhere (the bridge pins itself too),
# which also silences the "NVIDIA GPU may be present" notice.
ENV JAX_PLATFORMS=cpu

# Debian-patched pip refuses to replace RECORD-less apt packages such as numpy.
# Install a fresh pip, then let the gym's dependency stack (NumPy 2, JAX, ...)
# land in /usr/local, which takes precedence over the apt copies.
RUN pip3 install --ignore-installed pip

# The f1tenth_gym dependency lives outside /sim_ws/src so that bind-mounting
# this repo into the container (see docker-compose.yml) cannot shadow it. An
# editable install is required: the gym downloads tracks into its own maps/.
COPY --from=gym-src /sim_ws/f1tenth_gym /sim_ws/f1tenth_gym
RUN pip3 install --ignore-installed -e /sim_ws/f1tenth_gym

COPY . /sim_ws/src/f1tenth_gym_ros

RUN source /opt/ros/${ROS_DISTRO}/setup.bash && \
    apt-get update && \
    if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then \
        rosdep init; \
    fi && \
    rosdep update && \
    rosdep install -i --from-paths /sim_ws/src --rosdistro ${ROS_DISTRO} -y && \
    colcon build --symlink-install && \
    rm -rf /var/lib/apt/lists/*

# Interactive shells come up ready to `ros2 launch`
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc && \
    echo "source /sim_ws/install/setup.bash" >> /root/.bashrc

# foxglove_bridge websocket (connect Foxglove to ws://localhost:8765)
EXPOSE 8765

ENTRYPOINT ["/bin/bash"]
